version: '3.8'
services:
  api:
    image: leonidtuz/employeesv2-api
    build:
      context: ./EmployeesV2.Api
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=tuzdatabase;Username=leonid;Password=777project"
    ports:
      - "5000:80"

  client:
    image: leonidtuz/employeesv2-clientapp
    build:
      context: ./clientapp
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: leonid
      POSTGRES_PASSWORD: 777project
      POSTGRES_DB: tuzdatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client

volumes:
  db_data: