version: '3.8'
services:
  api:
    build:
      context: ./EmployeesV2/EmployeesV2.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=tuzdatabase;Username=leonid;Password=777project"

  client:
    build:
      context: ./EmployeesV2/clientapp
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: leonid
      POSTGRES_PASSWORD: 777project
      POSTGRES_DB: tuzdatabase
    ports:
      - "5432:5432"