version: '3.8'
services:
  api:
    image: leonidtuz/employeesv2-api:latest
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=tuzdatabase;Username=leonid;Password=777project"

  client:
    image: leonidtuz/employeesv2-clientapp:latest
    ports:
      - "3000:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: leonid
      POSTGRES_PASSWORD: 777project
      POSTGRES_DB: tuzdatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: