name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore ./EmployeesV2.Api.Tests/EmployeesV2.Api.Tests.csproj

      - name: Run tests
        run: dotnet test ./EmployeesV2.Api.Tests/EmployeesV2.Api.Tests.csproj --no-restore

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./EmployeesV2.Api
          file: ./EmployeesV2.Api/Dockerfile
          push: true
          tags: leonidtuz/employeesv2-api:${{ github.sha }}

      - name: Build and push Client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./clientapp
          file: ./clientapp/Dockerfile
          push: true
          tags: leonidtuz/employeesv2-clientapp:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tuz_project/EmployeesV2
            docker compose pull
            docker compose up -d